### ISSUE TITLE
[bug] Detection empty when using hash

### ISSUE THREAD

**Issue by 0xFustang** [AttackIQ/pySigma-backend-microsoft365defender#11]
## Description

When converting with a Sigma detection rule that includes `Hashes` I get the following error:

```bash
Error while conversion: Detection is empty
```

I've tested the same Sigma rule with the Splunk. I believe the backend should provide another error.

In addition, I tried to use `microsoft_365_defender_hashes_field_values` using a transforms.

```yaml
transformations:
  - id: hash_test
    type: set_state
    key: microsoft_365_defender_hashes_field_values
    val: True
    field_name_conditions:
    - type: include_fields
      fields:
      - Hashes
    rule_conditions:
      - type: logsource
        category: process_creation
        product: windows
```

## Reproduce

sigma-cli:

```bash
sigma convert -t microsoft_defender rules/windows/process_creation/proc_creation_win_renamed_paexec.yml
```

Sigma rules: 

- https://github.com/SigmaHQ/sigma/blob/f07e2b37c0919e0fb7b00eb1123d9a862e6466b4/rules/windows/process_creation/proc_creation_win_renamed_paexec.yml 
- https://github.com/SigmaHQ/sigma/blob/f07e2b37c0919e0fb7b00eb1123d9a862e6466b4/rules/windows/process_creation/proc_creation_win_lolbin_mpiexec.yml
