### ISSUE TITLE
Error with negation

### ISSUE THREAD

**Issue by rfackroyd** [AttackIQ/pySigma-backend-microsoft365defender#7]
Hey again.

This issue is on negation, where I am getting errors from MDE. I have converted the following test Sigma logic:

```
logsource:
  product: windows
  category: process_creation
detection:
  selection:
    Image:
      - '*\process.exe'
    CommandLine:
      - '*this*'
  filter:
    CommandLine:
      - '*notthis*'
  condition: selection and not filter
```

To this KQL:

```
DeviceProcessEvents
| where FolderPath endswith "\\process.exe" and ProcessCommandLine contains "this" and  !~  ProcessCommandLine contains "notthis"
```

I get red error marking underneath `and`:

_"A value of type 'bool' expected.(KS107)"_

And underneath '!~':

_"The incomplete fragment is unexpected.(KS198)"_

I wonder if we are using a string comparison operator `!~` when we may need to simply use `not`. Keen to hear your thoughts though.

When I correct the KQL manually to the following, I do not get the error. Note that I needed to add the parenthesis around the last condition (`ProcessCommandLine contains "notthis"`) to make it work.

```
DeviceProcessEvents
| where FolderPath endswith "\\process.exe" and ProcessCommandLine contains "this" and  not  (ProcessCommandLine contains "notthis")

```
