### ISSUE TITLE
Logic grouping 

### ISSUE THREAD

**Issue by rfackroyd** [AttackIQ/pySigma-backend-microsoft365defender#8]
Hi, this one is focussed on how grouping is applied, and how it seems to be affecting the logic

With the following code:

```
sigma_rule = SigmaRule.from_yaml("""
  title: Net connection logic test
  status: test
  logsource:
      category: network_connection
      product: windows
  detection:
      selection:
          Image:
            - '*\powershell.exe'
            - '*\pwsh.exe'
          DestinationHostname: 
            - '*pastebin.com*'
            - '*anothersite.com*'
      condition: selection
""")

m365def_backend = Microsoft365DefenderBackend()

pipeline = microsoft_365_defender_pipeline()
pipeline.apply(sigma_rule)

print(m365def_backend.convert_rule(sigma_rule)[0])
```

We get the KQL:

```
DeviceNetworkEvents
| where InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe" and RemoteUrl contains "pastebin.com" or RemoteUrl contains "anothersite.com"
```

Issue here is that this KQL simply detects all processes named 'powershell.exe' as the first condition checks out immediately 

The `mdatp.py` backend from Sigmatools whilst legacy seems to apply grouping here which means that both conditions in parenthesis must be true in order for an alert to arise

```
DeviceNetworkEvents 
| where ((InitiatingProcessFolderPath endswith @"\powershell.exe" or  InitiatingProcessFolderPath endswith @"\pwsh.exe") and (RemoteUrl contains "pastebin.com" or RemoteUrl contains "anothersite.com"))
```
